title: Marcelo Mantovani
logo: /assets/marcel.png
description: Atualmente cursando Jogos Digitais com foco em combinar expertise técnica com expressão artística.
show_downloads: false
theme: jekyll-theme-minimal
