title: Marcelo Mantovani
#logo: /assets/img/headshot_circle.png
description: Profissional dinâmico e versátil com experiência diversificada em arte digital, gestão de eventos e administração. Proficiente em uma ampla gama de ferramentas de software e linguagens de programação, habilidoso em solução criativa de problemas e comunicação eficaz. Atualmente cursando Bacharelado em Jogos Digitais e Habilidades de Programação, com foco em combinar expertise técnica com expressão artística
show_downloads: true
theme: jekyll-theme-minimal
